Repository LofftApp/lofft-web-client, pull requests merged in 2021-11, with the labels that each got.

#15 Updated the landing page to reflect the brand image of Lofft
  .github/pull_request_template.md
  public/favicon.ico
  public/favicon.png
  public/index.html
  src/components/Message.js
  src/components/Welcome.js
  src/logo.png
  src/styling/App.scss
  src/styling/components/_middleText.scss
Labels: enhancement

#19 Changed the year from 2021 to 2022
  src/components/Message.js
Labels: bug

#24 Demo: Added modal interaction on home page
  README.md
Labels: enhancement, Proposed feature

#30 Updated Yarn
  yarn.lock
Labels: bug

#32 Removed the NPM and Yarn packages and reinstalled through yarn
  yarn.lock
Labels: bug

#33 Updated server.js file with code bug issues and package.json with lat…
  .vscode/settings.json
  package.json
  server.js
  yarn.lock
Labels: Security

#34 Taglines
  src/clouds.svg
  src/components/LandingPage.js
  src/components/Taglines.js
  src/hands.svg
  src/lofftPeople.svg
  src/styling/App.scss
  src/styling/components/_buttons.scss
  src/styling/components/_taglineTile.scss
Labels: enhancement

#21 New People Section
  public/people/adam.png
  public/people/freddie.png
  public/people/ivo.png
  public/people/james.png
  public/people/leo.png
  public/people/valentin.png
  src/components/LandingPage.js
  src/components/People.js
  src/people.js
  src/styling/App.scss
  src/styling/components/_buttons.scss
  src/styling/components/_colors.scss
  src/styling/components/_people.scss
Labels: enhancement

#46 Refactor v1
  .github/CODE_OF_CONDUCT.md
  .github/LICENSE
  package.json
  public/icons/beach.svg
  public/icons/beer.svg
  public/icons/cat.svg
  public/icons/dog.svg
  public/icons/dribbble.svg
  public/icons/github.svg
  public/icons/instagram.svg
  public/icons/linkedin.svg
  public/icons/mountain.svg
  public/icons/movie.svg
  public/icons/podcast.svg
  public/icons/website.svg
  public/icons/wine.svg
  public/illustrations/clouds.svg
  public/illustrations/hands.svg
  public/illustrations/lofftPeople.svg
  public/illustrations/logo.svg
  public/illustrations/people.svg
  public/illustrations/textlogo.svg
  public/index.html
  public/manifest.json
  src/App.js
  src/App.test.js
  src/components/Banner.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Message.js
  src/components/People.js
  src/components/Taglines.js
  src/components/Welcome.js
  src/components/countdown.txt
  src/fonts/Archia/archia-regular-webfont.ttf
  src/index.css
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styling/App.scss
  src/styling/components/_animation.scss
  src/styling/components/_fonts.scss
  src/styling/components/_footer.scss
  src/styling/components/_middleText.scss
  src/styling/components/_people.scss
Labels: enhancement

#37 People popup styling
  src/components/LandingPage.js
  src/components/Modal.js
  src/components/People.js
  src/components/PeoplePopup.js
  src/components/Slider.js
  src/people.js
  src/styling/App.scss
  src/styling/components/_peoplePopup.scss
  src/styling/components/_slider.scss
Labels: enhancement

#53 Added google analytics
  package.json
  src/App.js
  yarn.lock
Labels: enhancement

#57 Updated the feature document
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation
